language: go

go:
  - stable

branches:
  only:
    - develop

script:
  - go env | grep GOCACHE | cut -d "=" -f 2
    "/home/travis/.cache/go-build"
  - cd Helper
  - go run .

after_success:
  - cd ..
  - git checkout -b gh
  - git config --local user.name "${U_NAME}"
  - git config --local user.email "${U_EMAIL}"
  - git add .
  - git commit -m ":construction_worker:- Build & Deploy by Travis CI"
  - git push --force "https://${Travis_Token}@${GIT_REF}" gh:master